"""Markdown documentation generator.

Natural-language sections (purpose, business logic) are produced by the LLM when a
gateway is supplied and flagged as inferred → requiring review. Structural facts
(dependencies, paragraphs, data items) are always derived deterministically from the
parser/graph and cite their source location.
"""

from __future__ import annotations

import json

from ..graph import DependencyGraph, EdgeType
from ..graph.emit import to_mermaid
from ..logging_setup import get_logger
from ..parsing.model import CobolProgram

log = get_logger()

_REVIEW_NOTE = (
    "> ⚠️ Sections marked _inferred_ were generated by an LLM and must be "
    "confirmed by a human before they are treated as authoritative.\n"
)


def _cite(rel_path: str | None, line: int) -> str:
    if not rel_path:
        return ""
    return f" (`{rel_path}:{line}`)" if line else f" (`{rel_path}`)"


class DocGenerator:
    def __init__(self, gateway=None):
        self.gateway = gateway

    # -- per-artifact ------------------------------------------------------- #
    def program_doc(
        self,
        program: CobolProgram,
        graph: DependencyGraph,
        rel_path: str,
        confidence: float,
    ) -> str:
        name = program.program_id or (rel_path.rsplit("/", 1)[-1])
        kind = "Copybook" if program.is_copybook else "Program"
        used_llm = False
        llm = self._llm_summary(name, program, rel_path)
        if llm is not None:
            used_llm = True

        lines: list[str] = [f"# {kind}: {name}", ""]
        lines.append(f"*Source:* `{rel_path}`  ")
        lines.append(f"*Type:* {kind.lower()} · *parse confidence:* {confidence:.2f}")
        if program.program_id_source == "llm":
            lines.append(" · *program id recovered by LLM (inferred)*")
        lines.append("")

        # Purpose
        lines.append("## Purpose")
        if llm and llm.get("purpose"):
            lines.append(f"_(inferred)_ {llm['purpose']}")
        else:
            lines.append(self._fallback_purpose(program, kind))
        lines.append("")

        # Dependencies
        lines.append("## Dependencies")
        lines.extend(self._dependency_lines(name, program, graph, rel_path))
        lines.append("")

        # Structure
        lines.append("## Structure")
        if program.divisions:
            lines.append(f"- **Divisions:** {', '.join(program.divisions)}")
        if program.paragraphs:
            lines.append(f"- **Paragraphs ({len(program.paragraphs)}):**")
            for p in program.paragraphs:
                tag = " _(inferred)_" if p.inferred else ""
                lines.append(f"  - `{p.name}`{_cite(rel_path, p.line)}{tag}")
        if program.data_items:
            lines.append(f"- **Data items ({len(program.data_items)}):**")
            for d in program.data_items:
                pic = f" PIC `{d.pic}`" if d.pic else ""
                lines.append(f"  - {d.level:02d} `{d.name}`{pic}{_cite(rel_path, d.line)}")
        lines.append("")

        # Business logic
        lines.append("## Business logic")
        if llm and llm.get("business_logic"):
            lines.append("_(inferred)_")
            for item in llm["business_logic"]:
                lines.append(f"- {item}")
        else:
            lines.append(self._fallback_business_logic(program))
        lines.append("")

        if used_llm or program.program_id_source == "llm" or any(p.inferred for p in program.paragraphs):
            lines.append(_REVIEW_NOTE)

        return "\n".join(lines) + "\n"

    def _dependency_lines(
        self, name: str, program: CobolProgram, graph: DependencyGraph, rel_path: str
    ) -> list[str]:
        out: list[str] = []
        if program.calls:
            for c in program.calls:
                kind = "dynamic CALL" if c.dynamic else "CALL"
                out.append(f"- {kind} → `{c.target}`{_cite(rel_path, c.line)}")
        if program.copies:
            for cp in program.copies:
                out.append(f"- COPY → `{cp.name}`{_cite(rel_path, cp.line)}")

        # Reverse dependencies from the graph (resolve keys to display names).
        def _disp(node_key: str) -> str:
            node = graph.nodes.get(node_key)
            return node.name if node else node_key

        callers = [_disp(e.src) for e in graph.edges if e.dst == name and e.type == EdgeType.call]
        jobs = [_disp(e.src) for e in graph.edges if e.dst == name and e.type == EdgeType.exec]
        if callers:
            out.append(f"- **Called by:** {', '.join(sorted(set(callers)))}")
        if jobs:
            out.append(f"- **Invoked by job(s):** {', '.join(sorted(set(jobs)))}")
        if not out:
            out.append("- _No dependencies detected._")
        return out

    @staticmethod
    def _fallback_purpose(program: CobolProgram, kind: str) -> str:
        bits = []
        if program.paragraphs:
            bits.append(f"{len(program.paragraphs)} paragraph(s)")
        if program.data_items:
            bits.append(f"{len(program.data_items)} data item(s)")
        if program.calls:
            bits.append(f"{len(program.calls)} CALL(s)")
        detail = ", ".join(bits) if bits else "no extracted structure"
        return f"{kind} containing {detail}. (Enable the LLM for a natural-language summary.)"

    @staticmethod
    def _fallback_business_logic(program: CobolProgram) -> str:
        if program.paragraphs:
            names = ", ".join(f"`{p.name}`" for p in program.paragraphs[:12])
            return f"Procedure flow (by paragraph): {names}."
        return "_Not generated (LLM disabled)._"

    def _llm_summary(self, name: str, program: CobolProgram, rel_path: str) -> dict | None:
        if self.gateway is None:
            return None
        from ..llm import CompletionRequest, Message

        skeleton = {
            "program_id": program.program_id,
            "paragraphs": [p.name for p in program.paragraphs],
            "data_items": [f"{d.level:02d} {d.name} {d.pic or ''}".strip() for d in program.data_items],
            "calls": [c.target for c in program.calls],
            "copies": [c.name for c in program.copies],
        }
        prompt = (
            "You are documenting a legacy COBOL artifact for modernization. Based on "
            "its extracted structure, return ONLY a JSON object: "
            '{"purpose": str, "business_logic": [str]}. '
            "purpose is one concise paragraph; business_logic is 3-6 bullet strings. "
            "Do not invent details not supported by the structure.\n\n"
            f"STRUCTURE for {name} ({rel_path}):\n{json.dumps(skeleton, indent=2)}"
        )
        try:
            resp = self.gateway.complete(
                "documentation", CompletionRequest(messages=[Message(role="user", content=prompt)])
            )
            data = _extract_json_object(resp.text)
            return data if isinstance(data, dict) else None
        except Exception as exc:
            log.warning("LLM documentation failed for %s: %s", name, exc)
            return None

    # -- system overview ---------------------------------------------------- #
    def overview(
        self,
        project_name: str,
        graph: DependencyGraph,
        doc_links: list[tuple[str, str, str]],  # (name, type, doc_filename)
        findings_summary: dict,
    ) -> str:
        from ..graph.model import NodeType

        counts: dict[str, int] = {}
        for node in graph.nodes.values():
            counts[node.type.value] = counts.get(node.type.value, 0) + 1

        lines = [f"# System Documentation: {project_name}", ""]
        lines.append("## Inventory")
        for t in (NodeType.program, NodeType.copybook, NodeType.job, NodeType.dataset, NodeType.external):
            if counts.get(t.value):
                lines.append(f"- **{t.value.capitalize()}:** {counts[t.value]}")
        lines.append("")

        lines.append("## Dependency graph")
        lines.append("```mermaid")
        lines.append(to_mermaid(graph).rstrip())
        lines.append("```")
        lines.append("")

        lines.append("## Security summary")
        lines.append(f"- **Total findings:** {findings_summary.get('total', 0)}")
        by_sev = findings_summary.get("by_severity", {})
        for sev in ("critical", "high", "medium", "low", "info"):
            if by_sev.get(sev):
                lines.append(f"  - {sev}: {by_sev[sev]}")
        lines.append(f"- **Require human review:** {findings_summary.get('requires_human_review', 0)}")
        lines.append("")

        lines.append("## Structural observations")
        cycles = graph.find_cycles()
        lines.append(f"- **Dependency cycles:** {len(cycles)}"
                     + (": " + "; ".join(" → ".join(c) for c in cycles) if cycles else ""))
        orphans = graph.orphans()
        lines.append(f"- **Orphan programs (no incoming refs):** {', '.join(orphans) if orphans else 'none'}")
        unused = graph.unused_copybooks()
        lines.append(f"- **Unused copybooks:** {', '.join(unused) if unused else 'none'}")
        unresolved = graph.unresolved_references()
        lines.append(f"- **Unresolved references:** {', '.join(unresolved) if unresolved else 'none'}")
        lines.append("")

        lines.append("## Artifacts")
        if doc_links:
            lines.append("| Name | Type | Documentation |")
            lines.append("| --- | --- | --- |")
            for name, type_, filename in sorted(doc_links):
                lines.append(f"| {name} | {type_} | [{filename}]({filename}) |")
        else:
            lines.append("_No documented artifacts._")
        lines.append("")
        return "\n".join(lines) + "\n"


def _extract_json_object(text: str) -> dict:
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ValueError("no JSON object in response")
    return json.loads(text[start : end + 1])
